variable "rg_name" {}
variable "loc_name" {}
variable "vnet_name" {}
variable "ipaddress" {}
variable "web-subnet" {}
variable "app-subnet" {}
variable "web-nsg" {}
variable "app-nsg" {}
variable "web-nic" {}
variable "app-nic" {}
variable "public-ip" {}
variable "public-lb" {}
variable "private-lb" {}
variable "nginx-vm" {}
variable "admin_username" {}
variable "admin_password" {}
variable "tomcat-vm" {}
variable "public-iplb" {}